# -*- coding: utf-8 -*-
"""TFG_Generacion_Datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QMwOhvscQEVygXAtEsJ4JwZW7BgNNeFc
"""

# Importamos pandas, que es la librería estándar en Ciencia de Datos para manejar tablas
import pandas as pd
# Importamos librerías para generar números aleatorios y fechas
import random
from datetime import datetime, timedelta

print("Librerías importadas correctamente. ¡Listo para empezar!")

import pandas as pd

# 1. Definimos la lista de recetas con las matemáticas ya procesadas (Reducción Unitaria)
# Notas de cálculo:
# Tamales = 300 unidades. Humitas = 120 unidades.
# 1 cucharada sal = 20g = 0.02kg. 1 cucharada pimenton = 10g = 0.01kg.

datos_recetas = [
    # --- RECETA DEL TAMAL ---
    {"ID_receta": "R01", "producto": "Tamal", "ingrediente": "Maiz pelado amarillo", "cantidad_por_unidad": 7 / 300, "unidad": "kg"},
    {"ID_receta": "R02", "producto": "Tamal", "ingrediente": "Carne de vaca", "cantidad_por_unidad": 4 / 300, "unidad": "kg"},
    {"ID_receta": "R03", "producto": "Tamal", "ingrediente": "Carne de cerdo", "cantidad_por_unidad": 4 / 300, "unidad": "kg"},
    {"ID_receta": "R04", "producto": "Tamal", "ingrediente": "Cebolla", "cantidad_por_unidad": 5 / 300, "unidad": "kg"},
    {"ID_receta": "R05", "producto": "Tamal", "ingrediente": "Papa", "cantidad_por_unidad": 5 / 300, "unidad": "kg"},
    # Grasas: 750g + 45g = 795g = 0.795 kg
    {"ID_receta": "R06", "producto": "Tamal", "ingrediente": "Grasa de cerdo", "cantidad_por_unidad": 0.795 / 300, "unidad": "kg"},
    {"ID_receta": "R07", "producto": "Tamal", "ingrediente": "Azucar", "cantidad_por_unidad": 0.200 / 300, "unidad": "kg"},
    # Sal fina total: 70g + 80g + 40g = 190g = 0.19 kg
    {"ID_receta": "R08", "producto": "Tamal", "ingrediente": "Sal fina", "cantidad_por_unidad": 0.190 / 300, "unidad": "kg"},
    # Sal gruesa: 180g = 0.18 kg
    {"ID_receta": "R09", "producto": "Tamal", "ingrediente": "Sal gruesa", "cantidad_por_unidad": 0.180 / 300, "unidad": "kg"},
    {"ID_receta": "R10", "producto": "Tamal", "ingrediente": "Caldo de gallina", "cantidad_por_unidad": 7 / 300, "unidad": "unidad"},
    {"ID_receta": "R11", "producto": "Tamal", "ingrediente": "Pimienta blanca", "cantidad_por_unidad": 0.040 / 300, "unidad": "kg"},
    {"ID_receta": "R12", "producto": "Tamal", "ingrediente": "Comino", "cantidad_por_unidad": 0.024 / 300, "unidad": "kg"},
    {"ID_receta": "R13", "producto": "Tamal", "ingrediente": "Aji locoto", "cantidad_por_unidad": 0.050 / 300, "unidad": "kg"},
    {"ID_receta": "R14", "producto": "Tamal", "ingrediente": "Pimenton rojo", "cantidad_por_unidad": 0.100 / 300, "unidad": "kg"},
    {"ID_receta": "R15", "producto": "Tamal", "ingrediente": "Hojas de chala", "cantidad_por_unidad": 2 / 300, "unidad": "kg"},
    {"ID_receta": "R16", "producto": "Tamal", "ingrediente": "Leña", "cantidad_por_unidad": 0.75 / 300, "unidad": "m2"},

    # --- RECETA DE LA HUMITA ---
    {"ID_receta": "R17", "producto": "Humita", "ingrediente": "Choclo blanco", "cantidad_por_unidad": 50 / 120, "unidad": "unidad"},
    {"ID_receta": "R18", "producto": "Humita", "ingrediente": "Queso de mesa", "cantidad_por_unidad": 1 / 120, "unidad": "kg"},
    {"ID_receta": "R19", "producto": "Humita", "ingrediente": "Leche", "cantidad_por_unidad": 0.5 / 120, "unidad": "L"},
    {"ID_receta": "R20", "producto": "Humita", "ingrediente": "Grasa de cerdo", "cantidad_por_unidad": 0.400 / 120, "unidad": "kg"},
    # Azucar: 400g + 200g = 600g = 0.6 kg
    {"ID_receta": "R21", "producto": "Humita", "ingrediente": "Azucar", "cantidad_por_unidad": 0.600 / 120, "unidad": "kg"},
    # Sal fina: 100g = 0.1 kg
    {"ID_receta": "R22", "producto": "Humita", "ingrediente": "Sal fina", "cantidad_por_unidad": 0.100 / 120, "unidad": "kg"},
    # Sal gruesa: 60g = 0.06 kg
    {"ID_receta": "R23", "producto": "Humita", "ingrediente": "Sal gruesa", "cantidad_por_unidad": 0.060 / 120, "unidad": "kg"},
    {"ID_receta": "R24", "producto": "Humita", "ingrediente": "Canela", "cantidad_por_unidad": 0.006 / 120, "unidad": "kg"},
    {"ID_receta": "R25", "producto": "Humita", "ingrediente": "Albahaca", "cantidad_por_unidad": 0.010 / 120, "unidad": "kg"},
    {"ID_receta": "R26", "producto": "Humita", "ingrediente": "Leña", "cantidad_por_unidad": 0.40 / 120, "unidad": "m2"}
]

# Convertimos la lista a un DataFrame de Pandas (Tabla)
df_recetas = pd.DataFrame(datos_recetas)

# Redondeamos los números largos a 6 decimales para que sea prolijo y matemáticamente exacto
df_recetas["cantidad_por_unidad"] = df_recetas["cantidad_por_unidad"].round(6)

print("¡Tabla RECETAS generada con éxito!")
display(df_recetas)

import pandas as pd
import random
from datetime import datetime, timedelta

# Diccionario de Precios Base (Los obtenidos en tu entrevista con la emprendedora)
precios_base = {
    "Maiz pelado amarillo": 2500.0, "Carne de vaca": 19000.0, "Carne de cerdo": 7000.0,
    "Cebolla": 666.67, "Papa": 1000.0, "Grasa de cerdo": 6666.67, "Azucar": 1500.0,
    "Sal fina": 600.0, "Sal gruesa": 500.0, "Caldo de gallina": 166.67,
    "Pimienta blanca": 6000.0, "Comino": 6000.0, "Aji locoto": 20000.0,
    "Pimenton rojo": 6000.0, "Hojas de chala": 22500.0, "Leña": 40000.0,
    "Choclo blanco": 440.0, "Queso de mesa": 11000.0, "Leche": 2000.0,
    "Canela": 33333.33, "Albahaca": 5000.0
}

registros_lotes = []
registros_ventas = []
registros_insumos = []

# Comenzamos la línea de tiempo simulada en Noviembre de 2025
fecha_acumulada = datetime(2025, 11, 1)

id_venta_contador = 1
id_compra_contador = 1

print("Iniciando motor de simulación para generar exactamente la escala del TFG...")

# BUCLE FIJO: Genera exactamente los 20 lotes declarados en la página 47 del TFG
for num_lote in range(1, 21):

    # Identificadores de lote para esta tanda quincenal/esporádica
    id_lote_t = f"L{num_lote:03d}-TAM"
    id_lote_h = f"L{num_lote:03d}-HUM"

    # 1. VOLUMEN DE PRODUCCIÓN (TFG Pág. 49: Base de 20 docenas con variación controlada de +-4 docenas)
    total_docenas = random.randint(16, 24)
    total_unidades = total_docenas * 12

    # Proporción operativa del negocio: se elaboran más tamales que humitas
    prod_tamal = int(total_unidades * random.uniform(0.65, 0.75))
    prod_humita = total_unidades - prod_tamal

    lotes_tanda = [
        {"id": id_lote_t, "prod": "Tamal", "cant": prod_tamal},
        {"id": id_lote_h, "prod": "Humita", "cant": prod_humita}
    ]

    for lote in lotes_tanda:
        if lote["cant"] <= 0: continue

        # 2. REGLA DE CONSISTENCIA (TFG Pág. 84: Unidades Producidas - Unidades Vendidas = Stock Remanente)
        # Asumimos una eficiencia comercial alta (vende entre el 90% y el 100% de la tanda fresca)
        ventas_totales = int(lote["cant"] * random.uniform(0.90, 1.0))
        stock_final = lote["cant"] - ventas_totales

        # Guardamos el registro del lote
        registros_lotes.append({
            "ID_lote": lote["id"],
            "fecha_produccion": fecha_acumulada.strftime("%Y-%m-%d"),
            "producto": lote["prod"],
            "unidades_producidas": lote["cant"],
            "stock_inicial": 0,
            "stock_final": stock_final
        })

        # 3. PATRÓN DE VENTA (TFG Pág. 49: Predominio de Feria y presencia ocasional de Pedidos)
        venta_feria = int(ventas_totales * 0.85)
        venta_pedido = ventas_totales - venta_feria

        # Precio de venta base
        precio_v_base = 2500 if lote["prod"] == "Tamal" else 2000
        # TFG Pág. 49: El precio de venta fluctúa uniformemente según la decisión estratégica en la feria
        precio_v_simulado = int(precio_v_base * random.uniform(0.95, 1.05))

        if venta_feria > 0:
            registros_ventas.append({
                "ID_venta": f"V{id_venta_contador:04d}", "ID_lote": lote["id"],
                "fecha_venta": (fecha_acumulada + timedelta(days=2)).strftime("%Y-%m-%d"),
                "producto": lote["prod"], "unidades_vendidas": venta_feria,
                "precio_unitario": precio_v_simulado, "canal": "Feria"
            })
            id_venta_contador += 1

        if venta_pedido > 0:
            registros_ventas.append({
                "ID_venta": f"V{id_venta_contador:04d}", "ID_lote": lote["id"],
                "fecha_venta": (fecha_actual_desvio := fecha_acumulada + timedelta(days=5)).strftime("%Y-%m-%d"),
                "producto": lote["prod"], "unidades_vendidas": venta_pedido,
                "precio_unitario": precio_v_simulado, "canal": "Pedido"
            })
            id_venta_contador += 1

        # 4. PRECIO DE INSUMOS (TFG Pág. 49: Fluctuación independiente y variación uniforme alrededor del costo base)
        receta_efectiva = df_recetas[df_recetas["producto"] == lote["prod"]]

        for index, fila in receta_efectiva.iterrows():
            ingrediente = fila["ingrediente"]
            cantidad_consumida = fila["cantidad_por_unidad"] * lote["cant"]

            # Simulamos la fluctuación de mercado aplicando una variación uniforme de +-10% al precio base
            precio_insumo_simulado = round(precios_base[ingrediente] * random.uniform(0.90, 1.10), 2)

            registros_insumos.append({
                "ID_compra": f"C{id_compra_contador:04d}",
                "fecha_compra": (fecha_acumulada - timedelta(days=1)).strftime("%Y-%m-%d"),
                "ingrediente": ingrediente,
                "cantidad": round(cantidad_consumida, 3),
                "unidad": fila["unidad"],
                "precio_unitario": precio_insumo_simulado
            })
            id_compra_contador += 1

    # 5. FRECUENCIA DE CICLOS (TFG Pág. 49: Intervalo variable por producción esporádica)
    # Hacemos avanzar el calendario entre 10 y 18 días para la siguiente tanda de producción
    dias_intervalo = random.randint(10, 18)
    fecha_acumulada += timedelta(days=dias_intervalo)

# Conversión a estructuras tabulares finales (DataFrames)
df_lotes = pd.DataFrame(registros_lotes)
df_ventas = pd.DataFrame(registros_ventas)
df_insumos = pd.DataFrame(registros_insumos)

# 6. VERIFICACIÓN PROGRAMÁTICA (Control de Calidad exigido en la Pág. 51 del TFG)
errores = 0
for idx, lote in df_lotes.iterrows():
    suma_ventas = df_ventas[df_ventas["ID_lote"] == lote["ID_lote"]]["unidades_vendidas"].sum()
    if (lote["unidades_producidas"] - suma_ventas) != lote["stock_final"]:
        errores += 1

if errores == 0:
    print(f"\n¡VALIDACIÓN EXITOSA!")
    print(f"Se han generado exactamente {len(df_lotes)} lotes comerciales, cumpliendo con la escala declarada.")
    print("La regla contable (Producción - Ventas = Stock Remanente) se cumple al 100% en cada registro.")

    # Exportación física a los archivos CSV requeridos
    df_lotes.to_csv("lotes.csv", index=False)
    df_ventas.to_csv("ventas.csv", index=False)
    df_insumos.to_csv("insumos.csv", index=False)
    df_recetas.to_csv("recetas.csv", index=False)
    print("Archivos listos para el Modelado Relacional. Proceda a su descarga.")
else:
    print(f"CRÍTICO: Se detectaron {errores} quiebres de consistencia en el balance de stock.")

import pandas as pd
import random
from datetime import datetime, timedelta

# Diccionario de Precios Base (Tus datos reales)
precios_base = {
    "Maiz pelado amarillo": 2500.0, "Carne de vaca": 19000.0, "Carne de cerdo": 7000.0,
    "Cebolla": 666.67, "Papa": 1000.0, "Grasa de cerdo": 6666.67, "Azucar": 1500.0,
    "Sal fina": 600.0, "Sal gruesa": 500.0, "Caldo de gallina": 166.67,
    "Pimienta blanca": 6000.0, "Comino": 6000.0, "Aji locoto": 20000.0,
    "Pimenton rojo": 6000.0, "Hojas de chala": 22500.0, "Leña": 40000.0,
    "Choclo blanco": 440.0, "Queso de mesa": 11000.0, "Leche": 2000.0,
    "Canela": 33333.33, "Albahaca": 5000.0
}

registros_lotes = []l
registros_ventas = []
registros_insumos = []

fecha_acumulada = datetime(2025, 11, 1)

id_venta_contador = 1
id_compra_contador = 1

print("Iniciando motor de simulación (20 ciclos productivos que generan 40 registros)...")

# Simular 20 ciclos de producción
for num_ciclo in range(1, 21):

    id_lote_t = f"L{num_ciclo:03d}-TAM"
    id_lote_h = f"L{num_ciclo:03d}-HUM"

    # 1. VOLUMEN: ~20 docenas (+-4) combinando ambos
    total_docenas = random.randint(16, 24)
    total_unidades = total_docenas * 12

    # 2. PROPORCIÓN: 70% tamales, 30% humitas aprox
    prod_tamal = int(total_unidades * random.uniform(0.65, 0.75))
    prod_humita = total_unidades - prod_tamal

    lotes_tanda = [
        {"id": id_lote_t, "prod": "Tamal", "cant": prod_tamal},
        {"id": id_lote_h, "prod": "Humita", "cant": prod_humita}
    ]

    for lote in lotes_tanda:
        if lote["cant"] <= 0: continue

        # 3. VENTAS Y CONSISTENCIA
        ventas_totales = int(lote["cant"] * random.uniform(0.90, 1.0))
        stock_final = lote["cant"] - ventas_totales

        registros_lotes.append({
            "ID_lote": lote["id"],
            "fecha_produccion": fecha_acumulada.strftime("%Y-%m-%d"),
            "producto": lote["prod"],
            "unidades_producidas": lote["cant"],
            "stock_inicial": 0,
            "stock_final": stock_final
        })

        # 4. CANALES Y PRECIOS
        venta_feria = int(ventas_totales * 0.85)
        venta_pedido = ventas_totales - venta_feria

        precio_v_base = 2500 if lote["prod"] == "Tamal" else 2000
        precio_v_simulado = int(precio_v_base * random.uniform(0.95, 1.05))

        if venta_feria > 0:
            registros_ventas.append({"ID_venta": f"V{id_venta_contador:04d}", "ID_lote": lote["id"], "fecha_venta": (fecha_acumulada + timedelta(days=2)).strftime("%Y-%m-%d"), "producto": lote["prod"], "unidades_vendidas": venta_feria, "precio_unitario": precio_v_simulado, "canal": "Feria"})
            id_venta_contador += 1

        if venta_pedido > 0:
            registros_ventas.append({"ID_venta": f"V{id_venta_contador:04d}", "ID_lote": lote["id"], "fecha_venta": (fecha_acumulada + timedelta(days=5)).strftime("%Y-%m-%d"), "producto": lote["prod"], "unidades_vendidas": venta_pedido, "precio_unitario": precio_v_simulado, "canal": "Pedido"})
            id_venta_contador += 1

        # 5. INSUMOS Y RECETAS
        receta_efectiva = df_recetas[df_recetas["producto"] == lote["prod"]]
        for index, fila in receta_efectiva.iterrows():
            ingrediente = fila["ingrediente"]
            cantidad_consumida = fila["cantidad_por_unidad"] * lote["cant"]

            precio_insumo_simulado = round(precios_base[ingrediente] * random.uniform(0.90, 1.10), 2)
            registros_insumos.append({"ID_compra": f"C{id_compra_contador:04d}", "fecha_compra": (fecha_acumulada - timedelta(days=1)).strftime("%Y-%m-%d"), "ingrediente": ingrediente, "cantidad": round(cantidad_consumida, 3), "unidad": fila["unidad"], "precio_unitario": precio_insumo_simulado})
            id_compra_contador += 1

    # 6. ESPORADICIDAD (Saltos de 10 a 18 días)
    dias_intervalo = random.randint(10, 18)
    fecha_acumulada += timedelta(days=dias_intervalo)

df_lotes = pd.DataFrame(registros_lotes)
df_ventas = pd.DataFrame(registros_ventas)
df_insumos = pd.DataFrame(registros_insumos)

errores = 0
for idx, lote in df_lotes.iterrows():
    suma_ventas = df_ventas[df_ventas["ID_lote"] == lote["ID_lote"]]["unidades_vendidas"].sum()
    if (lote["unidades_producidas"] - suma_ventas) != lote["stock_final"]:
        errores += 1

if errores == 0:
    print(f"\n¡VALIDACIÓN EXITOSA! Se generaron {len(df_lotes)} registros de lotes (40 filas).")
    df_lotes.to_csv("lotes.csv", index=False)
    df_ventas.to_csv("ventas.csv", index=False)
    df_insumos.to_csv("insumos.csv", index=False)
    df_recetas.to_csv("recetas.csv", index=False)
    print("Exportación de dataset sintético finalizada. Archivos CSV listos")
else:
    print("Hubo errores de consistencia.")

import pandas as pd
import random
from datetime import datetime, timedelta

# ==========================================
# 1. DICCIONARIO DE PRECIOS BASE (Tus datos reales)
# ==========================================
precios_base = {
    "Maiz pelado amarillo": 2500.0,
    "Carne de vaca": 19000.0,
    "Carne de cerdo": 7000.0,
    "Cebolla": 666.67,
    "Papa": 1000.0,
    "Grasa de cerdo": 6666.67,
    "Azucar": 1500.0,
    "Sal fina": 600.0,
    "Sal gruesa": 500.0,
    "Caldo de gallina": 166.67,
    "Pimienta blanca": 6000.0,
    "Comino": 6000.0,
    "Aji locoto": 20000.0,
    "Pimenton rojo": 6000.0,
    "Hojas de chala": 22500.0,
    "Leña": 40000.0,
    "Choclo blanco": 440.0,
    "Queso de mesa": 11000.0,
    "Leche": 2000.0,
    "Canela": 33333.33,
    "Albahaca": 5000.0
}

# ==========================================
# 2. DEFINIR LAS RECETAS (TODOS los ingredientes)
# ==========================================
datos_recetas = [
    # --- RECETA DEL TAMAL (para 300 unidades = 25 docenas) ---
    {"ID_receta": "R01", "producto": "Tamal", "ingrediente": "Maiz pelado amarillo", "cantidad_por_unidad": 7 / 300, "unidad": "kg"},
    {"ID_receta": "R02", "producto": "Tamal", "ingrediente": "Carne de vaca", "cantidad_por_unidad": 4 / 300, "unidad": "kg"},
    {"ID_receta": "R03", "producto": "Tamal", "ingrediente": "Carne de cerdo", "cantidad_por_unidad": 4 / 300, "unidad": "kg"},
    {"ID_receta": "R04", "producto": "Tamal", "ingrediente": "Cebolla", "cantidad_por_unidad": 5 / 300, "unidad": "kg"},
    {"ID_receta": "R05", "producto": "Tamal", "ingrediente": "Papa", "cantidad_por_unidad": 5 / 300, "unidad": "kg"},
    # Grasas: 750g + 45g = 795g = 0.795 kg
    {"ID_receta": "R06", "producto": "Tamal", "ingrediente": "Grasa de cerdo", "cantidad_por_unidad": 0.795 / 300, "unidad": "kg"},
    {"ID_receta": "R07", "producto": "Tamal", "ingrediente": "Azucar", "cantidad_por_unidad": 0.200 / 300, "unidad": "kg"},
    # Sal fina total: 70g + 80g + 40g = 190g = 0.19 kg
    {"ID_receta": "R08", "producto": "Tamal", "ingrediente": "Sal fina", "cantidad_por_unidad": 0.190 / 300, "unidad": "kg"},
    # Sal gruesa: 180g = 0.18 kg
    {"ID_receta": "R09", "producto": "Tamal", "ingrediente": "Sal gruesa", "cantidad_por_unidad": 0.180 / 300, "unidad": "kg"},
    {"ID_receta": "R10", "producto": "Tamal", "ingrediente": "Caldo de gallina", "cantidad_por_unidad": 7 / 300, "unidad": "unidad"},
    {"ID_receta": "R11", "producto": "Tamal", "ingrediente": "Pimienta blanca", "cantidad_por_unidad": 0.040 / 300, "unidad": "kg"},
    {"ID_receta": "R12", "producto": "Tamal", "ingrediente": "Comino", "cantidad_por_unidad": 0.024 / 300, "unidad": "kg"},
    {"ID_receta": "R13", "producto": "Tamal", "ingrediente": "Aji locoto", "cantidad_por_unidad": 0.050 / 300, "unidad": "kg"},
    {"ID_receta": "R14", "producto": "Tamal", "ingrediente": "Pimenton rojo", "cantidad_por_unidad": 0.100 / 300, "unidad": "kg"},
    {"ID_receta": "R15", "producto": "Tamal", "ingrediente": "Hojas de chala", "cantidad_por_unidad": 2 / 300, "unidad": "kg"},
    {"ID_receta": "R16", "producto": "Tamal", "ingrediente": "Leña", "cantidad_por_unidad": 0.75 / 300, "unidad": "m2"},

    # --- RECETA DE LA HUMITA (para 120 unidades = 10 docenas) ---
    {"ID_receta": "R17", "producto": "Humita", "ingrediente": "Choclo blanco", "cantidad_por_unidad": 50 / 120, "unidad": "unidad"},
    {"ID_receta": "R18", "producto": "Humita", "ingrediente": "Queso de mesa", "cantidad_por_unidad": 1 / 120, "unidad": "kg"},
    {"ID_receta": "R19", "producto": "Humita", "ingrediente": "Leche", "cantidad_por_unidad": 0.5 / 120, "unidad": "L"},
    {"ID_receta": "R20", "producto": "Humita", "ingrediente": "Grasa de cerdo", "cantidad_por_unidad": 0.400 / 120, "unidad": "kg"},
    # Azucar: 400g + 200g = 600g = 0.6 kg
    {"ID_receta": "R21", "producto": "Humita", "ingrediente": "Azucar", "cantidad_por_unidad": 0.600 / 120, "unidad": "kg"},
    # Sal fina: 100g = 0.1 kg
    {"ID_receta": "R22", "producto": "Humita", "ingrediente": "Sal fina", "cantidad_por_unidad": 0.100 / 120, "unidad": "kg"},
    # Sal gruesa: 60g = 0.06 kg
    {"ID_receta": "R23", "producto": "Humita", "ingrediente": "Sal gruesa", "cantidad_por_unidad": 0.060 / 120, "unidad": "kg"},
    {"ID_receta": "R24", "producto": "Humita", "ingrediente": "Canela", "cantidad_por_unidad": 0.006 / 120, "unidad": "kg"},
    {"ID_receta": "R25", "producto": "Humita", "ingrediente": "Albahaca", "cantidad_por_unidad": 0.010 / 120, "unidad": "kg"},
    {"ID_receta": "R26", "producto": "Humita", "ingrediente": "Leña", "cantidad_por_unidad": 0.40 / 120, "unidad": "m2"}
]

# Convertir a DataFrame y redondear a 6 decimales
df_recetas = pd.DataFrame(datos_recetas)
df_recetas["cantidad_por_unidad"] = df_recetas["cantidad_por_unidad"].round(6)

print("✅ Tabla RECETAS generada correctamente.")
print(df_recetas)

# ==========================================
# 3. SIMULACIÓN DE LOTES, VENTAS E INSUMOS
# ==========================================

registros_lotes = []
registros_ventas = []
registros_insumos = []

fecha_acumulada = datetime(2025, 11, 1)

id_venta_contador = 1
id_compra_contador = 1

print("Iniciando motor de simulación (20 ciclos productivos)...")

# Simular 20 ciclos de producción
for num_ciclo in range(1, 21):

    id_lote_t = f"L{num_ciclo:03d}-TAM"
    id_lote_h = f"L{num_ciclo:03d}-HUM"

    # 1. VOLUMEN: ~20 docenas (+-4) combinando ambos
    total_docenas = random.randint(16, 24)
    total_unidades = total_docenas * 12

    # 2. PROPORCIÓN: 70% tamales, 30% humitas aprox
    prod_tamal = int(total_unidades * random.uniform(0.65, 0.75))
    prod_humita = total_unidades - prod_tamal

    lotes_tanda = [
        {"id": id_lote_t, "prod": "Tamal", "cant": prod_tamal},
        {"id": id_lote_h, "prod": "Humita", "cant": prod_humita}
    ]

    for lote in lotes_tanda:
        if lote["cant"] <= 0:
            continue

        # 3. VENTAS Y CONSISTENCIA
        ventas_totales = int(lote["cant"] * random.uniform(0.90, 1.0))
        stock_final = lote["cant"] - ventas_totales

        registros_lotes.append({
            "ID_lote": lote["id"],
            "fecha_produccion": fecha_acumulada.strftime("%Y-%m-%d"),
            "producto": lote["prod"],
            "unidades_producidas": lote["cant"],
            "stock_inicial": 0,
            "stock_final": stock_final
        })

        # 4. CANALES Y PRECIOS
        venta_feria = int(ventas_totales * 0.85)
        venta_pedido = ventas_totales - venta_feria

        precio_v_base = 2500 if lote["prod"] == "Tamal" else 2000
        precio_v_simulado = int(precio_v_base * random.uniform(0.95, 1.05))

        if venta_feria > 0:
            registros_ventas.append({
                "ID_venta": f"V{id_venta_contador:04d}",
                "ID_lote": lote["id"],
                "fecha_venta": (fecha_acumulada + timedelta(days=2)).strftime("%Y-%m-%d"),
                "producto": lote["prod"],
                "unidades_vendidas": venta_feria,
                "precio_unitario": precio_v_simulado,
                "canal": "Feria"
            })
            id_venta_contador += 1

        if venta_pedido > 0:
            registros_ventas.append({
                "ID_venta": f"V{id_venta_contador:04d}",
                "ID_lote": lote["id"],
                "fecha_venta": (fecha_acumulada + timedelta(days=5)).strftime("%Y-%m-%d"),
                "producto": lote["prod"],
                "unidades_vendidas": venta_pedido,
                "precio_unitario": precio_v_simulado,
                "canal": "Pedido"
            })
            id_venta_contador += 1

        # 5. INSUMOS (usando df_recetas)
        receta_efectiva = df_recetas[df_recetas["producto"] == lote["prod"]]

        for index, fila in receta_efectiva.iterrows():
            ingrediente = fila["ingrediente"]
            cantidad_consumida = fila["cantidad_por_unidad"] * lote["cant"]

            precio_insumo_simulado = round(precios_base[ingrediente] * random.uniform(0.90, 1.10), 2)

            registros_insumos.append({
                "ID_compra": f"C{id_compra_contador:04d}",
                "fecha_compra": (fecha_acumulada - timedelta(days=1)).strftime("%Y-%m-%d"),
                "ingrediente": ingrediente,
                "cantidad": round(cantidad_consumida, 3),
                "unidad": fila["unidad"],
                "precio_unitario": precio_insumo_simulado
            })
            id_compra_contador += 1

    # 6. ESPORADICIDAD (Saltos de 10 a 18 días)
    dias_intervalo = random.randint(10, 18)
    fecha_acumulada += timedelta(days=dias_intervalo)

# ==========================================
# 4. CONVERTIR A DATAFRAMES
# ==========================================
df_lotes = pd.DataFrame(registros_lotes)
df_ventas = pd.DataFrame(registros_ventas)
df_insumos = pd.DataFrame(registros_insumos)

# ==========================================
# 5. VALIDACIÓN DE CONSISTENCIA
# ==========================================
errores = 0
for idx, lote in df_lotes.iterrows():
    suma_ventas = df_ventas[df_ventas["ID_lote"] == lote["ID_lote"]]["unidades_vendidas"].sum()
    if (lote["unidades_producidas"] - suma_ventas) != lote["stock_final"]:
        errores += 1

# ==========================================
# 6. EXPORTACIÓN
# ==========================================
if errores == 0:
    print(f"\n✅ ¡VALIDACIÓN EXITOSA!")
    print(f"Se generaron {len(df_lotes)} registros de lotes.")
    print("La regla contable (Producción - Ventas = Stock Remanente) se cumple al 100%.")

    df_lotes.to_csv("lotes.csv", index=False)
    df_ventas.to_csv("ventas.csv", index=False)
    df_insumos.to_csv("insumos.csv", index=False)
    df_recetas.to_csv("recetas.csv", index=False)

    print("\n📁 ARCHIVOS CSV GENERADOS:")
    print("- lotes.csv")
    print("- ventas.csv")
    print("- insumos.csv")
    print("- recetas.csv")
    print("¡Listos para importar en Power BI!")
else:
    print(f"❌ CRÍTICO: Se detectaron {errores} quiebres de consistencia.")

import pandas as pd
import os

# Crear directorio para las plantillas si no existe
output_dir = 'plantillas_csv'
os.makedirs(output_dir, exist_ok=True)

# 1. Estructura para LOTES
df_lotes = pd.DataFrame({
    'ID_lote': ['L-001'],
    'fecha_produccion': ['2025-01-15'],
    'producto': ['Tamal'],
    'unidades_producidas': [150],
    'stock_inicial': [0],
    'stock_final': [10]
})

# 2. Estructura para VENTAS
df_ventas = pd.DataFrame({
    'ID_venta': ['V-0001'],
    'ID_lote': ['L-001'],
    'producto': ['Tamal'],
    'unidades_vendidas': [12],
    'precio_unitario': [1200.50],
    'canal': ['Feria']
})

# 3. Estructura para INSUMOS
df_insumos = pd.DataFrame({
    'ID_compra': ['C-001'],
    'ID_lote': ['L-001'],
    'ingrediente': ['Carne de vaca'],
    'cantidad': [2.5],
    'unidad': ['kg'],
    'precio_unitario': [6500.00]
})

# 4. Estructura para RECETAS
df_recetas = pd.DataFrame({
    'ID_receta': ['R-001'],
    'producto': ['Tamal'],
    'ingrediente': ['Carne de vaca'],
    'cantidad_por_unidad': [0.035],
    'unidad': ['kg']
})

# Exportar a CSV (sin la columna de índice)
df_lotes.to_csv(f'{output_dir}/lotes_template.csv', index=False, encoding='utf-8')
df_ventas.to_csv(f'{output_dir}/ventas_template.csv', index=False, encoding='utf-8')
df_insumos.to_csv(f'{output_dir}/insumos_template.csv', index=False, encoding='utf-8')
df_recetas.to_csv(f'{output_dir}/recetas_template.csv', index=False, encoding='utf-8')

print("Plantillas CSV generadas exitosamente en la carpeta 'plantillas_csv'.")